name: Build tagged Debian images

on:
  push:
    tags: ["debian-*"]

env:
  OS: debian
  DOCKER_REPO: ilyes512/php74-fpm

jobs:
  build_tagged_debian:
    name: Build tagged Debian
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set TAG-env
        run: echo ::set-env name=TAG::$(echo $GITHUB_REF | cut -d / -f 3-)
      - name: Output TAG-env
        run: 'echo "\$TAG: $TAG"'
      - uses: docker/build-push-action@v1
        with:
          repository: ${{ env.DOCKER_REPO }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          dockerfile: ${{ env.OS }}/Dockerfile
          target: builder
          add_git_labels: true
          tag: ${{ env.TAG }}-builder
          tag_with_sha: true
      - uses: docker/build-push-action@v1
        with:
          repository: ${{ env.DOCKER_REPO }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          dockerfile: ${{ env.OS }}/Dockerfile
          target: runtime
          add_git_labels: true
          tag: ${{ env.TAG }}-runtime
          tag_with_sha: true
